### ISSUE TITLE
question: about Observable subscription dispose in the View Models

### ISSUE THREAD

**Issue by KevinHu-au** [RLittlesII/ReactiveUI.Showroom#1]
Instead of an actual issue here, I have a question regarding the observable subscription dispose in the View Models.
Not sure if it is appropriate to ask a question here.

When I was playing with this repo, I found most of the observable subscriptions in the view models are ending with call DisposeWith().

Take InfiniteScrollViewModel.cs as an example (#47 - #77)
```
            _inventoryDataService
                .ChangeSet
                .Transform(x =>
                    new InventoryItemViewModel
                    {
                        Id = x.Id,
                        Brand = x.BrandName,
                        Coffee = x.CoffeeName,
                        Roast = x.Roast,
                        Packaging = x.Packaging
                    })
                .AutoRefresh(x => x.Id)
                .DeferUntilLoaded()
                .Filter(searchChanged)
                .Sort(SortExpressionComparer<InventoryItemViewModel>.Descending(x => x.Roast))
                .Page(_pagingSubject.AsObservable())
                .ObserveOn(RxApp.MainThreadScheduler)
                .Bind(out _items)
                .DisposeMany()
                .Subscribe()
                .DisposeWith(ViewModelSubscriptions);

            this.WhenAnyObservable(x => x.Refresh.IsExecuting)
                .StartWith(false)
                .DistinctUntilChanged()
                .ToProperty(this, nameof(IsRefreshing), out _isRefreshing, deferSubscription: true)
                .DisposeWith(ViewModelSubscriptions);

            this.WhenAnyObservable(x => x.Load.IsExecuting)
                .ToProperty(this, nameof(IsLoading), out _isLoading, deferSubscription: true)
                .DisposeWith(ViewModelSubscriptions);
```
By reading the document from ReactiveUI [https://www.reactiveui.net/docs/guidelines/framework/dispose-your-subscriptions](url), it seems like the last two subscriptions are unnecessary to dispose. But the first one is necessary as it will cause the VM to have the reference with _inventoryDataService.

Not sure if my understanding is correct. Thanks for clarification.

**Comment by RLittlesII** [comment]
The technique I am using here is different from the documentation.  Notice the `WhenActivated` would be tied to the ViewModel's life cycle.

```
this.WhenActivated(
    disposables =>
    {
        this.WhenAnyValue(...)
            .DisposeWith(disposables);
    });
```

I am explicitly not using the `WhenActivated` block for various reasons.  So I am not sure this is an apples to apples comparison given I am not using `WhenActivated`.  As a general rule of thumb, I clean up everything when the ViewModel is disposed as you will see on the [ViewModelBase](https://github.com/RLittlesII/ReactiveUI.Showroom/blob/d579bceff27d541f401a630e007b5e6ab6cccfee/src/Forms/Base/ViewModelBase.cs#L47-L53).

Whether it is overkill or not could be questioned further I am sure.

About this being the wrong place, meh.  Just use the `question: ` prefix next time.  [slack](https://reactiveui.net/slack) is also. a good place to get questions answered.

**Comment by KevinHu-au** [comment]
@RLittlesII , Thanks for your clarification. I was thinking to ask the question in the slack channel, but as it is specific to this showroom sample. Any I knew it is kind of inappropriate to raise a question here. Anyway, thanks again @RLittlesII .

**Comment by RLittlesII** [comment]
I'd rather you get an answer and break the rules than have a question unanswered and follow them.  Feel free to ask questions.  Not your fault GitHub calls them issues!
@KevinHu-au
